---
- name: Remove sysctl.d configuration based on files
  become: true
  ansible.builtin.file:
    path: "{{ sysctl_sysctld_path }}/{{ item | basename }}"
    state: absent
  with_fileglob:
    - "{{ sysctl_local_sysctld_path }}/*.conf"

- name: Remove sysctl.d configuration based on templates
  become: true
  ansible.builtin.file:
    path: "{{ sysctl_sysctld_path }}/{{ item | basename | splitext | first }}"
    state: absent
  with_fileglob:
    - "{{ sysctl_local_sysctld_path }}/*.conf.j2"
