---
- name: Copy sysctl.d files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ sysctl_sysctld_path }}"
    mode: "{{ sysctl_file_mode }}"
    force: true
  with_fileglob:
    - "{{ sysctl_local_sysctld_path }}/*.conf"
  register: copied_files
  notify:
    - reload configuration