---
- name: Copy sysctl.d files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ sysctl_sysctld_path }}"
    mode: "{{ sysctl_file_mode }}"
    force: true
  with_fileglob:
    - "{{ sysctl_local_sysctld_path }}/*.conf"
  register: copied_files
  notify:
    - reload configuration based on files

- name: Copy sysctl.d templates
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ sysctl_sysctld_path }}/{{  item | basename | splitext | first }}"
    mode: "{{ sysctl_file_mode }}"
    force: true
  with_fileglob:
    - "{{ sysctl_local_sysctld_path }}/*.conf.j2"
  register: copied_templates
  notify:
    - reload configuration based on templates
