---
- name: reload configuration based on files
  become: true
  ansible.builtin.command:
    cmd: "/usr/sbin/sysctl -p {{ item }}"
  loop: "{{ copied_files.results | selectattr('changed', 'equalto', true) | map(attribute='dest') | list }}"

- name: reload configuration based on templates
  become: true
  ansible.builtin.command:
    cmd: "/usr/sbin/sysctl -p {{ item }}"
  loop: "{{ copied_templates.results | selectattr('changed', 'equalto', true) | map(attribute='dest') | list }}"
