---
- name: reload configuration
  become: true
  ansible.builtin.command:
    cmd: "/usr/sbin/sysctl -p {{ item }}"
  loop: "{{ copied_files.results | selectattr('changed', 'equalto', true) | map(attribute='dest') | list }}"
